import TrunookXPC
import AppKit

/// Следит за системным буфером обмена.
///
/// Уведомления об изменении буфера macOS не рассылает вовсе — остаётся
/// опрашивать `changeCount`. Это одно целое число, четырежды в секунду,
/// на энергопотреблении не сказывается.
final class ClipboardMonitor {
    var onCopy: ((ClipboardEntry) -> Void)?

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount

    /// Изображение крупнее этого не сохраняем: история должна оставаться
    /// лёгкой, а снимок экрана в несколько мегабайт в ней не нужен.
    private static let maxImageBytes = 6 * 1024 * 1024

    /// Флаги менеджеров паролей и служебных копирований.
    ///
    /// `ConcealedType` ставят менеджеры паролей — такое не сохраняем никогда.
    /// `TransientType` и `AutoGeneratedType` помечают содержимое, которое
    /// в истории заведомо не нужно.
    private static let skipTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    func start() {
        guard timer == nil else { return }
        lastChangeCount = NSPasteboard.general.changeCount
        let timer = Timer(timeInterval: 0.25, repeats: true) { [weak self] _ in
            self?.check()
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
        DebugLog.write("буфер: наблюдение начато")
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func check() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        // Приложение только что само трогало буфер — это не копирование
        // пользователя, и в историю оно не идёт.
        guard !PasteboardActivity.isQuiet else { return }

        let present = Set(pasteboard.types ?? [])
        if let flag = Self.skipTypes.first(where: { present.contains($0) }) {
            DebugLog.write("буфер: пропущено, помечено как \(flag.rawValue)")
            return
        }

        guard let entry = read(pasteboard) else { return }
        DebugLog.write("буфер: \(entry.kind.rawValue) из \(entry.source ?? "неизвестно")"
                       + ", \(entry.oneLine.prefix(40))")
        onCopy?(entry)
    }

    private func read(_ pasteboard: NSPasteboard) -> ClipboardEntry? {
        let source = NSWorkspace.shared.frontmostApplication?.localizedName

        // Порядок важен: у скопированного из Finder файла есть и адрес,
        // и имя строкой, а интересует именно файл.
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [
            .urlReadingFileURLsOnly: true,
        ]) as? [URL], !urls.isEmpty {
            return ClipboardEntry(
                id: 0,
                kind: .files,
                text: urls.map(\.path).joined(separator: "\n"),
                data: nil,
                source: source,
                copiedAt: Date()
            )
        }

        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return ClipboardEntry(
                id: 0,
                kind: .text,
                text: text,
                data: nil,
                source: source,
                copiedAt: Date()
            )
        }

        if let image = NSImage(pasteboard: pasteboard), let png = Self.png(from: image) {
            guard png.count <= Self.maxImageBytes else {
                DebugLog.write("буфер: изображение \(png.count / 1024) КБ — крупнее потолка, пропущено")
                return nil
            }
            return ClipboardEntry(
                id: 0,
                kind: .image,
                text: tf("Изображение %d×%d", Int(image.size.width), Int(image.size.height)),
                data: png,
                source: source,
                copiedAt: Date()
            )
        }

        return nil
    }

    /// PNG, а не исходное представление: буфер отдаёт TIFF без сжатия,
    /// и снимок экрана занял бы в базе десятки мегабайт.
    private static func png(from image: NSImage) -> Data? {
        guard let tiff = image.tiffRepresentation,
              let bitmap = NSBitmapImageRep(data: tiff)
        else { return nil }
        return bitmap.representation(using: .png, properties: [:])
    }
}
